# Map from Varner terminology to BiGG keys
varner_to_ijo = {'5pbdra': 'pram',
                'faicar': 'fprica',
                '78dhf': 'dhpt',
                '78mdp': '6hmhptpp',
                'cadav': '15dap',
                'cair': '5aizc',
                'clasp': 'cbp',
                'fgar': 'fgam',
                'gaba': '4abut',
                'glycoA': 'gcald',
                'nh3': 'nh4',
                'he': 'h',
                'omp': 'orot5p',
                 'or': 'orot',
                 'prop': 'ppcoa',
                 'mglx': 'mthgxl',
                 'saicar': '25aics',
                 '4adochor': '4adcho'
                }
